// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBySuNrilYH55k9OKZPddoaBRUVJEtoq_s',
    appId: '1:588317464409:web:fb0e469f79e6c3f618de48',
    messagingSenderId: '588317464409',
    projectId: 'imagimate-92699',
    authDomain: 'imagimate-92699.firebaseapp.com',
    storageBucket: 'imagimate-92699.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoH00yp03U_047juUbPSYcog2jVA182Dg',
    appId: '1:588317464409:android:dffa37d4bfe5cddc18de48',
    messagingSenderId: '588317464409',
    projectId: 'imagimate-92699',
    storageBucket: 'imagimate-92699.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxJKW5Uwrp0iRBhAqexxl_ETTcmr4uw54',
    appId: '1:588317464409:ios:88fa1171ed8ab71818de48',
    messagingSenderId: '588317464409',
    projectId: 'imagimate-92699',
    storageBucket: 'imagimate-92699.appspot.com',
    iosBundleId: 'com.example.imagimate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxJKW5Uwrp0iRBhAqexxl_ETTcmr4uw54',
    appId: '1:588317464409:ios:9db834911c0d47d118de48',
    messagingSenderId: '588317464409',
    projectId: 'imagimate-92699',
    storageBucket: 'imagimate-92699.appspot.com',
    iosBundleId: 'com.example.imagimate.RunnerTests',
  );
}
